name: Sync to Hugging Face Space

on:
  push:
    branches: [radianda, main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push Subfolder Backend ke Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
        run: |
          cd backend_ML
          
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          
          git init -b main
          git add .
          git commit -m "Deploy: Sinkronisasi otomatis dari GitHub Actions"
          
          # Menggunakan variabel $HF_TOKEN dari env block di atas
          git push --force https://chicknug19:${HF_TOKEN}@huggingface.co/spaces/chicknug19/aol-ml main